### ISSUE TITLE
Bubble up all the console activity to the terminal output

### ISSUE THREAD

**Issue by abhagta-sfdc** [salesforce/lightning-labs#12]
Change the default behavior such that errors that occur in the browser context are showing in the terminal output.

**Comment by divmain** [comment]
- Old behavior
  - Default: do not show browser console output in the terminal
  - `--console` shows all browser console output in the terminal
- New behavior
  - Default: show all browser console output in the terminal
  - `--quiet` do not show browser console output in the terminal
